### PR TITLE
reset updates. del button working

### PR DESCRIPTION
**Pull request by jjg-akers**
I had to comment out line 9 in routes.py to get it to run locally.  That line tries to load a file in kiosk.py that you have stored in your c: directory. Is there anyway we can get around this?

### CODE REVIEW

**Comment by jjg-akers** [comment]
Also, I added __pycache__/ to the gitignore

**Comment by Pasmuth** [comment]
That is a key file for the Google Sheets API. I originally had it in the repo, but then google yelled at me saying that it found my key just by searching the internet and that it's now compromised. This is another file that I'll have to add to the .gitignore.

You may need to help me out as I learn some of the finer points of git operations. I'm sure that I'm doing a lot of stuff wrong.

**Comment by Pasmuth** [comment]
I'm having trouble merging these. It says I need to merge from the command line. I think I have to clone your branch into my local repo, then go line by line and make the required changes.

I tried `git fetch git@github.com:jjg-akers/hrdc-db.git serviceDeleteBtn:servDelBtn`

but I got the following message: 
`git@github.com: Permission denied (publickey).`
`    fatal: Could not read from remote repository.`
`
    Please make sure you have the correct access rights
    and the repository exists.`

What should I try next?

**Comment by jjg-akers** [comment]
Hey peter,
I’m really not sure. When I put in the pull request it said there wasn’t any issues.
I’m not at my computer right now but I’ll look at in this afternoon.

**Pull request closed without merging**
